version: '2.3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8088:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
      database-network:
        aliases:
          - mongo-express
    restart: always

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      database-network:
        aliases:
          - adminer
    restart: always

networks:
  database-network:
    external: true