version: '2.3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile/nginx.Dockerfile
    depends_on:
      - service-gateway
    entrypoint: ["nginx", "-g", "daemon off;"]
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000"
    networks:
      nginx-network:
        aliases:
          - nginx
    restart: always

networks:
  nginx-network:
    external: true